version: '3.5'

services:
  next-dev:
    container_name: next-dev
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    image: next-dev:latest
    ports:
      - 3000
    labels:
      traefik.enable: true
      traefik.http.routers.next-dev-redirect.rule: Host(`next.dev.webnsurf.com`)
      traefik.http.routers.next-dev-redirect.middlewares: https-redirect@file
      traefik.http.routers.next-dev-redirect.entrypoints: web

      traefik.http.routers.next-dev.rule: Host(`next.dev.webnsurf.com`)
      traefik.http.routers.next-dev.entrypoints: websecure
      traefik.http.routers.next-dev.tls: true
    volumes:
      - /app/dist
      - /app/node_modules
      - $PWD:/app
    environment:
      - NODE_ENV=development

networks:
  default:
    external:
      name: webnsurf_network
